export { createShortcuts } from './runtime/createRuntime'
export { commonBrowserShortcuts } from './presets/browser/common'
export { chromeBrowserShortcuts } from './presets/browser/chrome'
export { edgeBrowserShortcuts } from './presets/browser/edge'
export { firefoxBrowserShortcuts } from './presets/browser/firefox'
export { safariBrowserShortcuts } from './presets/browser/safari'
export { linuxOsShortcuts } from './presets/os/linux'
export { macOsShortcuts } from './presets/os/mac'
export { windowsOsShortcuts } from './presets/os/windows'
export type * from './types/public'
